### ISSUE TITLE
检测到实例启动后在极短的时间内退出，原因可能是您的启动命令错误或配置文件错误。

### ISSUE THREAD

**Issue by KingBillSame** [LiamSho/mcsmanager-image#1]
环境：Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)
使用文档中提供的docker run命令运行。
已经安装环境镜像JDK17，并在进程启动方式中配置好虚拟化容器启动。
使用一键快速开服中的Minecraft 1.19.2[整合包/Java&基岩版互通] 小型服务器推荐，互通基岩版，包含基础插件、箱子锁、操作回滚、领地和商店等插件。

实例控制台：
[MCSMANAGER] [INFO] 正在准备启动实例...
[MCSMANAGER] [ERROR] 检测到实例启动后在极短的时间内退出，原因可能是您的启动命令错误或配置文件错误。

alisaqaq/mcsmanager-daemon日志：
7:48:54] [[32mINFO[39m] ----------------
7:48:54] [[32mINFO[39m] Session pjyeTjg_W9PvKaDoAAAD: Request to start an instance
7:48:54] [[32mINFO[39m] UUID: [40cf5dcc11ae411c9f6e7950cc298063] [RouTine]
7:48:54] [[32mINFO[39m] NAME: [JDK17]
7:48:54] [[32mINFO[39m] COMMAND: java -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar nogui
7:48:54] [[32mINFO[39m] WORKSPACE: /opt/mcsmanager/daemon/data/InstanceData/40cf5dcc11ae411c9f6e7950cc298063
7:48:54] [[32mINFO[39m] NET_MODE: bridge
7:48:54] [[32mINFO[39m] OPEN_PORT: {"25565/tcp":[{"HostPort":"25565"}],"25565/udp":[{"HostPort":"25565"}],"19132/tcp":[{"HostPort":"19132"}],"19132/udp":[{"HostPort":"19132"}]}
7:48:54] [[32mINFO[39m] EXT_MOUNT: []
7:48:54] [[32mINFO[39m] NET_ALIASES: []
7:48:54] [[32mINFO[39m] MEM_LIMIT: undefined MB
7:48:54] [[32mINFO[39m] TYPE: Docker Container
7:48:54] [[32mINFO[39m] ----------------
7:48:55] [[32mINFO[39m] 实例 RouTine 40cf5dcc11ae411c9f6e7950cc298063 启动成功
7:48:55] [[91mERROR[39m] Error: UnhandledRejection: Error: (HTTP code 409) unexpected - Container e14f006c15746a7f11d09bec6157de215b3bef836f54942e4e9233a225a8891b is not running 
opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:301:17
etCause (/opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:331:7)
odem.buildPayload (/opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:300:5)
ncomingMessage. (/opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:275:14)
ncomingMessage.emit (events.js:412:35)
ndReadableNT (internal/streams/readable.js:1333:12)
rocessTicksAndRejections (internal/process/task_queues.js:82:21) {
: undefined,
Code: 409,
{
age: 'Container e14f006c15746a7f11d09bec6157de215b3bef836f54942e4e9233a225a8891b is not running'
  }
e {
ted> Error: (HTTP code 409) unexpected - Container e14f006c15746a7f11d09bec6157de215b3bef836f54942e4e9233a225a8891b is not running 
 /opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:301:17
 getCause (/opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:331:7)
 Modem.buildPayload (/opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:300:5)
 IncomingMessage. (/opt/mcsmanager/daemon/node_modules/docker-modem/lib/modem.js:275:14)
 IncomingMessage.emit (events.js:412:35)
 endReadableNT (internal/streams/readable.js:1333:12)
 processTicksAndRejections (internal/process/task_queues.js:82:21) {
on: undefined,
usCode: 409,
: {
ssage: 'Container e14f006c15746a7f11d09bec6157de215b3bef836f54942e4e9233a225a8891b is not running'
    }
  }
}

**Comment by AlisaAkiron** [comment]
运行MC的容器启动失败，检查一下你的服务器配置，要么是MCSM的问题，要么是你配置的问题，和这个MCSM的镜像没有关系

**Comment by KingBillSame** [comment]
> 运行MC的容器启动失败，检查一下你的服务器配置，要么是MCSM的问题，要么是你配置的问题，和这个MCSM的镜像没有关系

当我填写启动参数，如java -jar server.jar nogui，则会像这样显示无法启动。但当我删去启动参数，则能正常运行jdk容器。

**Comment by AlisaAkiron** [comment]
那不就是 JDK 镜像有问题吗（

**Comment by AlisaAkiron** [comment]
给你一个我用的 Dockerfile 用作参考，这个是带 Python 的

``` dockerfile
FROM python:3.10.8-bullseye

RUN /bin/mkdir /workspace

WORKDIR /workspace

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt update && apt install -y openjdk-17-jre curl wget locales locales-all

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

RUN apt autoremove -y && apt clean && rm -rf /var/lib/apt/lists/*

RUN pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple
```

**Comment by KingBillSame** [comment]
> 给你一个我用的 Dockerfile 用作参考，这个是带 Python 的
> 
> ```dockerfile
> FROM python:3.10.8-bullseye
> 
> RUN /bin/mkdir /workspace
> 
> WORKDIR /workspace
> 
> RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
> 
> RUN apt update && apt install -y openjdk-17-jre curl wget locales locales-all
> 
> ENV LC_ALL en_US.UTF-8
> ENV LANG en_US.UTF-8
> ENV LANGUAGE en_US.UTF-8
> 
> RUN apt autoremove -y && apt clean && rm -rf /var/lib/apt/lists/*
> 
> RUN pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple
> ```

感谢，原来是这个意思。因为我是用mcsm里面提供的jdk17镜像，没想到是自带的有问题。
